export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const FETCH_USER_ACTIVE_CHATS = "FETCH__USER_ACTIVE_CHATS";
export const FETCH_USER_ARCHIVED_CHATS = "FETCH__USER_ARCHIVED_CHATS";
export const FETCH_USER_STATS = "FETCH_USER_STATS";
export const FETCH_USER_WEEKLY_STATS = "FETCH_USER_WEEKLY_STATS";
export const FETCH_USER_ADDITIONAL_DETAILS="FETCH_USER_ADDITIONAL_DETAILS";